[PATCH] USB: fix dvb-ttusb-budget driver due to set_configuration locking cleanups
> Oops, you forgot to grep:
>
> CC [M]  drivers/media/dvb/ttusb-dec/ttusb_dec.o
> drivers/media/dvb/ttusb-budget/dvb-ttusb-budget.c: In function `ttusb_setup_interfaces':
> drivers/media/dvb/ttusb-budget/dvb-ttusb-budget.c:1011: warning: implicit declaration of function `usb_set_configuration'

Well, when I did the grep that bug wasn't there; it
was just integrated on Feb 26!


> Care to send a patch to fix it up before Andrew gets grumpy with me for
> breaking his build?  :)

The first part makes it use usb_reset_configuration() like
it did before ... I'm surprised this driver hasn't been
generating "it deadlocks during probe" reports.

The second part prints a diagnostic if the configuration
wasn't set right; the fix would use hotplug and sysfs.