[PATCH] nfsd needs exportfs
With NFSD=y, EXPORTFS=m:

fs/built-in.o(.text+0x7fff5): In function `fh_verify':
/usr/src/25/fs/nfsd/nfsfh.c:221: undefined reference to `export_op_default'

So it seems that nfsd requires exportfs.

For consistency we should tidy up the definition of EXPORTFS too.

Signed-off-by: Neil Brown <neilb@cse.unsw.edu.au>
Signed-off-by: Andrew Morton <akpm@osdl.org>
Signed-off-by: Linus Torvalds <torvalds@osdl.org>